services:
  tesfafund.api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5208:5208"
      - "7179:7179"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5208
    depends_on:
      - tesfafund.mongodb
    networks:
      - app-network

  tesfafund.mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: OmitUserOrPasswordToConnectWithoutAuth
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge